name: algolia_places
description: Algolia Places API https://community.algolia.com/places/documentation.html
version: 0.0.1
author: Raisel Melian <raisel.melian@gmail.com>
homepage: https://github.com/rmelian/algolia-places-dart
maintainer: Raisel Melian (@raiselmelian)

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  http: ">=0.11.0 <1.0.0"
  meta: ^1.1.0

dev_dependencies:
  test: ^1.3.0
  pedantic: ^1.4.0
  coverage: ^0.12.2
  test_coverage: ^0.2.3
